mission display infos
TheEmidee/UEMissionSystem pull request #29
Opened 2024-08-06 09:31 UTC by TheEmidee

- **Added Name and description to the mission data**
- **Added delegates on the mission system to let BPs know when mission and objective start and end**
- **Added CompleteObjective function**
- **Renamed delegates / events**
- **Created view model for UMG**

2024-08-06 09:52 UTC, Frickerson requested changes

2024-08-06 09:52 UTC, VectorGamez commented on Source/MissionSystem/Private/ViewModels/MSObjectiveViewModel.cpp
> +#include "Templates/SubclassOf.h"
<>

2024-08-06 10:03 UTC, jagged-teeth commented on Source/MissionSystem/Private/MSMissionSystem.cpp
>  #include "Serialization/ObjectAndNameAsStringProxyArchive.h"
unused include ?

2024-08-06 10:03 UTC, jagged-teeth commented on Source/MissionSystem/Private/ViewModels/MSViewModel.cpp
> +void UMSViewModel::SetMissionEnded( UMSMission * mission )
`const UMSMission * mission` on most of these functions would maybe be beneficial

2024-08-06 12:12 UTC, TheEmidee commented on Source/MissionSystem/Private/MSMissionSystem.cpp
>  #include "Serialization/ObjectAndNameAsStringProxyArchive.h"
done

2024-08-06 12:12 UTC, TheEmidee commented on Source/MissionSystem/Private/ViewModels/MSObjectiveViewModel.cpp
> +#include "Templates/SubclassOf.h"
done

2024-08-06 12:13 UTC, TheEmidee commented on Source/MissionSystem/Private/ViewModels/MSViewModel.cpp
> +void UMSViewModel::SetMissionEnded( UMSMission * mission )
wont fix as this can escalate quickly with const pointers in UE

2024-08-06 21:39 UTC, VectorGamez submitted a review, later dismissed

2024-08-07 06:36 UTC, jagged-teeth approved these changes

2024-08-12 08:51 UTC, merged