mission system component
TheEmidee/UEMissionSystem pull request #33
Opened 2024-08-29 13:24 UTC by TheEmidee

- Replaced mission system by a component
- Removed unused functions
- Give mission actions an outer for GetWorld()

2024-08-30 07:03 UTC, VectorGamez requested changes

2024-08-30 07:03 UTC, Frickerson commented on Source/MissionSystem/Private/MSMissionSystemComponent.cpp
> +#include "Engine/GameInstance.h"
<>

2024-08-30 07:03 UTC, Frickerson commented on Source/MissionSystem/Private/MSMissionSystemComponent.cpp
> +        /*if ( const auto * mission_system = world->GetSubsystem< UMSMissionSystemComponent >() )
Should maybe add a todo for all these commented functions?

2024-10-02 08:33 UTC, TheEmidee commented on Source/MissionSystem/Private/MSMissionSystemComponent.cpp
> +#include "Engine/GameInstance.h"
done

2024-10-02 08:35 UTC, TheEmidee commented on Source/MissionSystem/Private/MSMissionSystemComponent.cpp
> +        /*if ( const auto * mission_system = world->GetSubsystem< UMSMissionSystemComponent >() )
done

2024-10-02 08:38 UTC, merged